### ISSUE TITLE
libvirt triggering qemu segfault

### ISSUE THREAD

**Issue by wdsun1008** [AMDESE/qemu#12]
I am experiencing an issue where libvirt triggering qemu results in a segfault. When I try to start an SNP-enabled VM using libvirt, the startup fails. After checking the dmesg logs, I found that qemu experienced a segfault. 

```shell
[ 8418.356520] qemu-system-i38[74529]: segfault at 0 ip 0000563b14cfeb97 sp 00007fffbe91dfe0 error 4 in qemu-system-i386[563b1491e000+571000] likely on CPU 1 (core 1, socket 0)
[ 8418.356543] Code: 83 c4 08 48 89 de 5b 5d e9 c6 4b c2 ff 66 0f 1f 44 00 00 f3 0f 1e fa 41 55 49 89 d5 41 54 49 89 f4 55 48 89 fd 53 48 83 ec 08 <48> 8b 3f e8 31 fe ff ff 48 89 c3 48 85 c0 74 11 48 83 c4 08 48 89
[ 8418.872872] qemu-system-x86[74541]: segfault at 0 ip 000055aec7deca87 sp 00007ffed953e900 error 4 in qemu-system-x86_64[55aec79c7000+5de000] likely on CPU 1 (core 1, socket 0)
[ 8418.872893] Code: 83 c4 08 48 89 de 5b 5d e9 26 15 be ff 66 0f 1f 44 00 00 f3 0f 1e fa 41 55 49 89 d5 41 54 49 89 f4 55 48 89 fd 53 48 83 ec 08 <48> 8b 3f e8 31 fe ff ff 48 89 c3 48 85 c0 74 11 48 83 c4 08 48 
```

According to the libvirt logs, the qemu monitor connection got disconnected right after executing the 'query-sev-capabilities' command. 

```shell
Jul 26 08:21:21 ubuntu libvirtd[134476]: QEMU_MONITOR_SEND_MSG: mon=0x7fc47800a460 msg={"execute":"query-sev-capabilities","id":"libvirt-44"}
                                          fd=-1
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: QEMU_MONITOR_IO_WRITE: mon=0x7fc47800a460 buf={"execute":"query-sev-capabilities","id":"libvirt-44"}
                                          len=56 ret=56 errno=0
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_UNREF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_UNREF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: Unable to read from monitor: Connection reset by peer
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_UNREF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_UNREF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: OBJECT_REF: obj=0x7fc47800a460
Jul 26 08:21:21 ubuntu libvirtd[134476]: Failed to probe capabilities for /usr/local/bin/qemu-system-i386: Unable to read from monitor: Connection reset by peer
```

However, I could not reproduce this behavior on VMs that were started using the launch_qemu script. Upon investigating the libvirt qemu startup command, I discovered that libvirt would start a non-SNP enabled VM first to perform some checks, and it was during this process that qemu crashed. 

```shell
/usr/local/bin/qemu-system-x86_64 -S -no-user-config -nodefaults -nographic -machine none,accel=kvm:tcg -qmp unix:/var/lib/libvirt/qemu/qmp-JQ5G81/qmp.monitor,server=on,wait=off -pidfile /var/lib/libvirt/qemu/qmp-JQ5G81/qmp.pid -daemonize
```

By using gdb to obtain the call stack and based on the location of the error, I tried out a possible fix [qemu/11](https://github.com/AMDESE/qemu/pull/11)which successfully started the SNP-enabled VM.

```shell
Thread 1 "qemu-system-x86" received signal SIGSEGV, Segmentation fault.
object_property_find_err (obj=0x0, name=0x555555f5089f "sev-device", errp=0x5555566d24a0 <error_abort>) at ../qom/object.c:1312
1312        ObjectProperty *prop = object_property_find(obj, name);
(gdb) where
#0  object_property_find_err
    (obj=0x0, name=0x555555f5089f "sev-device", errp=0x5555566d24a0 <error_abort>) at ../qom/object.c:1312
#1  0x0000555555c7c08a in object_property_get
    (obj=obj@entry=0x0, name=name@entry=0x555555f5089f "sev-device", v=v@entry=0x5555569c4c10, errp=errp@entry=0x5555566d24a0 <error_abort>)
    at ../qom/object.c:1389
#2  0x0000555555c7f6b0 in object_property_get_qobject
    (obj=obj@entry=0x0, name=name@entry=0x555555f5089f "sev-device", errp=errp@entry=0x5555566d24a0 <error_abort>) at ../qom/qom-qobject.c:40
#3  0x0000555555c7c6e7 in object_property_get_str
    (obj=obj@entry=0x0, name=name@entry=0x555555f5089f "sev-device", errp=0x5555566d24a0 <error_abort>) at ../qom/object.c:1437
#4  0x0000555555ab8bef in sev_get_capabilities (errp=0x7fffffffdbf8)
    at ../target/i386/sev.c:1009
#5  qmp_query_sev_capabilities (errp=errp@entry=0x7fffffffdbf8)
    at ../target/i386/sev.c:1053
#6  0x0000555555c6f735 in qmp_marshal_query_sev_capabilities
    (args=<optimized out>, ret=0x7ffff5ea6e98, errp=0x7ffff5ea6e90)
    at qapi/qapi-commands-misc-target.c:236
#7  0x0000555555ddd2ad in do_qmp_dispatch_bh (opaque=0x7ffff5ea6ea0)
    at ../qapi/qmp-dispatch.c:128
#8  0x0000555555dfc135 in aio_bh_call (bh=0x5555569c1f10)
    at ../util/async.c:155
#9  aio_bh_poll (ctx=ctx@entry=0x55555676a7d0) at ../util/async.c:184
#10 0x0000555555de6ee2 in aio_dispatch (ctx=0x55555676a7d0)
    at ../util/aio-posix.c:421
#11 0x0000555555dfbd92 in aio_ctx_dispatch
    (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../util/async.c:326
#12 0x00007ffff7952569 in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x0000555555dfd6f8 in glib_pollfds_poll ()
    at ../util/main-loop.c:290
#14 os_host_main_loop_wait (timeout=0) at ../util/main-loop.c:313
#15 main_loop_wait (nonblocking=nonblocking@entry=0)
    at ../util/main-loop.c:592
#16 0x0000555555a417e3 in qemu_main_loop ()
    at ../softmmu/runstate.c:731
#17 0x00005555558630da in qemu_default_main () at ../softmmu/main.c:37
#18 0x00007ffff7423510 in __libc_start_call_main
     (main=main@entry=0x55555585e220 <main>, argc=argc@entry=11, argv=argv@entry=0x7fffffffdf68) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007ffff74235c9 in __libc_start_main_impl
     (main=0x55555585e220 <main>, argc=11, argv=0x7fffffffdf68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf58) at ../csu/libc-start.c:381
#20 0x0000555555863005 in _start ()
```

**Comment by mdroth** [comment]
Thanks for the report. Your proposed fix looks appropriate so I've applied it to qemu snp-latest tree.

**Comment by tlendacky** [comment]
Yes, we had that fix in the snp-v3 tree, just didn't bring it forward.

There currently isn't support for SNP via libvirt, @wdsun1008 are you working on that?

**Comment by wdsun1008** [comment]
> Yes, we had that fix in the snp-v3 tree, just didn't bring it forward.
> 
> There currently isn't support for SNP via libvirt, @wdsun1008 are you working on that?

Yes, I'm using libvirt 9.5.0, snp-latest host kernel/qemu/ovmf(OvmfPkg/AmdSev/AmdSevX64.dsc), ubuntu kinetic based guest OS.
After solving [#173](https://github.com/AMDESE/AMDSEV/issues/173)and this issue, all the VMs looks good for now.

**Comment by wzrdtales** [comment]
Did libvirt already work for you? @wdsun1008 Even when supplied the correct params to qemu as manual params libvirt ends up with a crashed qemu complaining

```
2024-04-06T19:15:44.431236Z qemu-system-x86_64: -accel kvm: sev_kvm_init: Failed to open /dev/sev 'No such file or directory'
2024-04-06T19:15:44.456550Z qemu-system-x86_64: -accel kvm: failed to initialize kvm: Operation not permitted
```
